---
title: Tools for Engineering Design
---

School: School of Engineering

College: College of Science and Engineering


# Summary


This course introduces students to a wide range of skills that are required in civil/mechanical engineering design, and that make part of the engineers' toolbox. It provides students with experience of solving and communicating solutions to open-ended engineering problems that require compromise between competing criteria and priorities. It develops competence and confidence in communication skills including sketching, engineering drawings and oral presentation. It also introduces engineering tools such as basic CAD and spreadsheet skills via self-directed learning.

# Course description  

Engineers design things. The 'things' that engineers design range from mile-high skyscrapers to underwater vehicles, from flood prevention schemes for informal settlements, to wind turbines, from single use PPE for hospitals to 100-year city strategies. We design things that need to fit into and strengthen our existing infrastructure. Engineering, therefore, is fundamentally creative, and Tools for Engineering Design 2 helps develop the skills needed for Engineering Design.


A key aspect of design is that there are no single correct answers. It is relatively straightforward to come up with a solution that works; the challenge for a good designer is to come up with the 'best' solution. That is not straightforward: some solutions might be impractical or unsafe to build, some might use materials that cannot be found locally, some will be very expensive or poor aesthetically. Designers often work with incomplete information, a Client who changes their mind part way through the project, or contradicting requirements. Iteration is always needed to find the 'best' design solution.

Tools for Engineering Design 2 helps students develop a 'toolbox' of strategies for tackling open-ended design problems. The course introduces the challenges of iterative design through short group projects and tasks. The projects gradually build students' awareness of and confidence in tackling conceptual design problems, a thread that is fundamental through engineering degree programmes. 

The course covers:

- What is design?

- Communication (drawings, group work, meetings, discussion)

- Self-led learning exercises

- Design, build, re-design project

- Master planning project

- Upgrade project

- Reflection exercise on what you have learnt on this course. 

As well as learning about the design process, students learn specific skills required by a designer: how drawings can be used at different stages of design; good team-working practices; and using simple tools to optimise solutions.

The course is taught through project work with discussion and critique of the various projects providing feedback to develop students' design skills.


# Timing: 


[Timetable](https://www.ted.is.ed.ac.uk/UOE2223_SWS/TIMETABLE.ASP?OBJECTCLASS=MODULE&IDENTIFIER=CIVE08020_SV1_SEM2&STYLE=TEXTSPREADSHEET&TEMPLATE=SWSCUST+OBJECT+TEXTSPREADSHEET&WEEK=26-37)

Total Hours: 100 (Supervised Practical/Workshop/Studio Hours 33, Formative Assessment Hours 1, Summative Assessment Hours 10, Programme Level Learning and Teaching Hours 2, Directed Learning and Independent Learning Hours 54)

# Assessment

Written Exam 0%,

Coursework
100%,

Practical Exam
0%

Additional Information (Assessment)

100% coursework, largely based upon group work and requires attendance during timetabled hours.

Group:

Project 1 20%

Project 2 20%

Individual:

Self Learning Exercises 30%

Reflection Question Exercise 30%


Feedback

Group and class feedback takes place within discussion sessions in the timetabled hours. Verbal feedback will be given upon each group's design project submissions, and each group will be asked to keep a written record of this feedback.

# Learning Outcomes

On completion of this course, the student will be able to:

Tackle the challenge of creative open-ended design, including iteration, compromise, conflict, uncertainty, optimisation, research, choice, team-work and communication.Identify the explicit, implicit, and underlying drivers that govern a design problem and create conceptual design techniques to develop solutions that best satisfy these competing demands.Apply engineering tools to tackle complex design problems, typical of those found in engineering design.Communicate using different styles of basic drawings (sketches, technical drawings, CAD) and verbal communication (within or outwith the design team).Develop self-learning skills and the ability to apply these skills in sensible, self-critical way, including conducting and recording engineering calculations and software.


Reading List

[Expedition Workshed website](http://expeditionworkshed.org)

[Draft and Craft with AutoCAD - LinkedIn Learning](http://www.ucl.ac.uk/drawing-gym/)

From the course Learn site:

Ibell T. (2016) Virtual by design, The Structural Engineer, 94 (3), 88 89

Wise C.M. (2008). The call of the wild: the next 100 years, The Structural Engineer, 86(14), pp. 146 153


Additional Class Delivery Information

The course requires attendance at and participation in all of the weekly project sessions.  Non-attendance without good reason will result in an individual student's mark being reduced for group design work.

# Contacts

Course organiser: Dr David Rush

Tel: (0131 6)50 6023

Email: D.Rush@ed.ac.uk

Course secretary: Mr Craig Hovell

Tel: (0131 6)51 7080

Email: c.hovell@ed.ac.uk