---
title: Engineering Dynamics 2
---

| School | School of Engineering |
| College | College of science and engineering|

# Summary

This course aims to provide a basic understanding of the Laws of Newtonian Mechanics for bodies and systems of bodies in plane motion, and to achieve proficiency in their use in conjunction with kinematic principles for a range of mechanical engineering applications.


1. Dynamics of Particles
    

Newton's Laws of Motion and the nature of forces; D'Alembert approach; dynamical laws of single particle; dynamical theorems for systems of particles; Linear and Angular momentum; mass centre properties; motion in polar coordinates; Coriolis acceleration. Central Force motion and orbits.

2. Systems of Bodies

Rigid body as a model; dynamical laws for rigid bodies in pure translation, fixed axis rotation and general plane motion; inertia couple; moments of inertia; inertia theorems; rolling versus sliding. Kinematic relations between interacting bodies: circular motion, gear drives, belts and pulleys, rolling on a plane. Applications to coupled systems, power transmission, simple vehicles, rotational unbalance, static and dynamic-balancing of rotors; introduce balancing of reciprocating mechanisms.


3. Work - Energy Approach

Kinetic and potential energy; work and power; work-energy theorems applied to system calculations; the conservative system as a special case.

4. Oscillatory Motion

Introduction to oscillations; differential equations of translational and rotational SDF systems, free vibration, natural frequency; damping and critical damping; introduction to resonance, features of vibratory phenomena.

5. Gyroscopic Torque

Introduction to gyroscopic torque and gyroscopic effects; angular momentum vector of a rotor; precession applications.

# Course Load

Total Hours: 100

(Lecture Hours 20, Seminar/Tutorial Hours 9, Supervised Practical/Workshop/Studio Hours 1.5, Formative Assessment Hours 1, Summative Assessment Hours 3.5, Programme Level Learning and Teaching Hours 2, Directed Learning and Independent Learning Hours 63)

Assessment (Further Info)

Written Exam 50%, Coursework 50%, Practical Exam 0%

Additional Information (Assessment)

Degree Examination 50%; Coursework 50%

The School has a 40% Rule for 1st and 2nd year courses, i.e. you must achieve a minimum of 40% in coursework and 40% in written exam components, as well as an overall mark of 40% to pass a course. If you fail a course you will be required to resit it. You are only required to resit components which have been failed.

Practical Exam

# Learning Outcomes

Upon completion of the course, the student will be able to:

Model mechanical systems as plane assemblies of masses and inertias, and draw clear accurate linked free-body diagrams.Identify kinematic relations between coupled elements using cables, gears and pure rolling.Calculate moments of inertias of a range of assemblies, using parallel axes and perpendicular axes theorems.Formulate energy expressions for systems and use concepts of work and power to determine motion.Understand the properties of single degree of freedom oscillatory systems, and the importance of resonant systems in engineering.

Course URL

http://www.see.ed.ac.uk/teaching/mech/


Contacts

Course organiser: Dr John Chick

Tel: (0131 6)50 5675

Email: John.Chick@ed.ac.uk

Course secretary: Miss Chloe Fleming

Email: cflemin7@ed.ac.uk