---
title: Dimensional Analysis with Linear Algebra
subtitle: "Exploration of Buckingham's Pi Theorem"
author: Jasper Day
colorlinks: true
number-sections: true
---

[Source](http://homepage.math.uiowa.edu/~rcurtu/MathBioGroup/MBGfiles/dimAnalysis.pdf)

Buckingham's Pi theorem states that any relations between natural quantities can be expressed in an equivalent form using *Pi groups*, dimensionless quantities formed between those quantities.

# Assumptions:

The following assumptions must hold:

1. $\textit{u}$, our quantity of interest, must equal some function $f\left(x_{1}, x_{2}, x_{3}, \ldots, x_{n}\right)$, that is, $\textit{n}$ measurable quantities expressed as independent variables & parameters $x_{i}$. It is further assumed that the equation

$$
u = f\left(x_{1}, x_{2}, x_{3}, \ldots, x_{n}\right)
$$ 
is dimensionally homogeneous.

2. The quantities $\{u, x_{1}, x_{2}, x_{3}, \ldots, x_{n}\}$ are measured in terms of $\text{m}$ fundamental dimensions $\{ L_{1}, L_{2}, L_{3}, \ldots, L_{n} \}$

3. If $\text{W}$ is any quantity of $\{ u, x_{1}, \ldots, x_{n}\}$, then

$$
\left[W\right] = L_{1}^{p_{1}} \cdot L_{2}^{p_{2}} \cdot \ldots \cdot L_{m}^{p_{m}}
$$

Then we can create $\textbf{P} = \begin{bmatrix}p_{1} \\ p_{2} \\ \vdots \\ p_{m} \\\end{bmatrix}$, the *dimension vector* of W.

This gives us the $m\times n$ dimension matrix

$$
\textbf{A} = \begin{bmatrix} \textbf{P}_{1} | \textbf{P}_{2} | \cdots | \textbf{P}_{n} \\ \end{bmatrix} = \begin{bmatrix}
    p_{11} & p_{12} & \cdots & p_{1n} \\
    p_{21} & p_{22} & \cdots & p_{2n} \\
    \vdots & \vdots & \vdots & \vdots \\
    p_{m1} & p_{m2} & \cdots & p_{mn} \\
    \end{bmatrix}
$$

# Conclusions of the Buckingham Pi Theorem

1. The relation $u = f\left(x_{1}, x_{2}, \ldots, x_{n} \right)$ can be expressed in terms of dimensionless quantities.

2. The number of dimensionless quantities is

$$
k + 1 = n + 1 - \texttt{rank}\left(A\right)
$$

(The reason for k + 1 is that we pull out the original quantity $u$ from the matrix $\textbf{A}$. Otherwise this term would not appear.)

3. Since $\textbf{A}$ has $\texttt{rank}\left(A\right) = n - k$, there are $k$ linearly independent solutions of $\textbf{Az} = \textbf{0}$ denoted as $z^{1}, z^{2}, \ldots, z^{k}$.

Let $\textbf{a}$, an $m$-column vector, be the dimension vector of $u$, and let $\textbf{y}$, an $n$-column vector, be a solution of 

$$
\textbf{Ay} = -\textbf{a}
$$

Then the relation $u = f\left(x_{1}, x_{2}, \ldots, x_{n} \right)$ simplifies to $g\left(\Pi_{1}, \Pi_{2}, \ldots, \Pi_{k} \right)$.

There is one $\Pi$ group for each linearly indepenent set of $\textbf{Az} = \textbf{0}$, plus one $\Pi$ group for $u$. The parameters in each pi group are raised to the respective row of $z\prime$.

# Why it Works:

Recall that the nullspace of a matrix $\textbf{A}$ is the space of all vectors $\textbf{z}$ for which $\textbf{Az} = \textbf{0}$. The multiplication $\textbf{Az}$ is a linear combinations of the columns of $\textbf{A}$:

$$
\textbf{Az} = \left[
    z_{1}\textbf{P}_{1} | z_{2}\textbf{P}_{2} | \ldots | z_{n}\textbf{P}_{n}
\right]
$$

This linear combination of the columns of $\textbf{A}$ is the same thing that you get when you raise each of the parameters $x_{n}$ to the respective element of $\textbf{z}$:

$$
\left[x_{i}^{z_{i}}\right] = \left[W\right]^{z_{i}} =
    \left(L_{1}^{p_{1}} \cdot L_{2}^{p_{2}} \cdot \ldots \cdot L_{m}^{p_{m}}\right)^{z_{i}} =
    L_{1}^{p_{1}z_{i}} \cdot L_{2}^{p_{2}z_{i}} \cdot \ldots \cdot L_{m}^{p_{m}z_{i}}
$$

Which corresponds to column $i$ of $\textbf{Az}$. Finally, since $\textbf{z}$ is in the nullspace of $\textbf{A}$, the sum of the powers on each of the base units $L$ will be 0, resulting in an overall dimensionless quantity.
