---
title: Journalism As A Profession
author: Jasper Day
date: Mon 02/13/2023 
format:
  pdf:
    documentclass: scrartcl
csl: D:/documents/csl_citation_styles/ieee.csl
bibliography: journalism.bib
---

<!-- The task:

Select an occupation and discuss whether the occupation can be considered a profession.

- select an occupation
- showcase your understanding of the occupation in relation to the social and protectionist view
- consider each of the attributes of a profession and the degree to which your chosen occupation does or does not accord with these.

Do not exceed 2 pages of A4.

-->

\clearpage

# Introduction

Journalism exists in a tension between its moral imperative to provide the public with accurate and impartial information, and the challenges of regulating an industry without compromising free speech. Journalists provide a public service, informing citizens about the events and issues that affect their lives, holding those in power accountable, and contributing to democracy. But the traditional means through which such "sacred goods" are protected -- by government licensing and exclusionary regimes -- cannot be reasonably implemented in the case of journalism, because licensing would have a chilling effect on free speech. Liberal democracy cannot sustain a monopoly on the dissemination of news. Thus, although it seems to many people that journalism ought to be morally regulated, at least by some form of self-regulation, any attempt to create institutions that could enact such regulation would conflict with Western free speech norms. This essay will examine the tension created by the incompatible desires for freedom of speech and social accountability in journalism, and explore the different approaches that have been taken to resolving this tension in different parts of the world.

# Social Morality

Journalists provide an important social good by making news and discussion available to a broad range of people. Since this information often affects people's lives, scholars consider the news and discussion generated by journalists to be of *social importance* [@timvos2018, p. 4]. Clearly, reporting the actions of governments, businesses and private individuals serves as a useful and important check on abuses of power. As such, the free press has been of great historic importance. Since the Enlightenment, Western societies have recognized the importance of free and unfettered speech, which has manifested in fewer and fewer restrictions on what journalists can publish. However, concomitant with relaxed restrictions, people have worried about the dangers to free speech of commercialization and consolidation [@timvos2018, p. 28].

# Self-Organization

A profession is a self-organized group of workers who operate with autonomy, set codes of ethics, and exclude others from performing their work. Often they will have an exclusive charter from the government, and anyone seeking to engage the services done by professionals will have no option but to choose a professional. The codes of ethics set by professionals suggest their moral obligation to society in performing their services; the autonomy and self-organization suggest work performed to a high standard under the influence of a collective conscience [@aquinn2018]. Journalists similarly undertook some self-organization in the mid-20^th^ century, selling themselves as objective reporters of facts in the public interest [@aquinn2018] [@timvos2018, p. 27].

The American Society of Professional Journalists, for example, publishes a code of ethics that encourages objective and prosocial reporting [@spj]. It has some 6,000 members. On their website, they advertise their conferences, their training programs, and their code of ethics - but *not* improved employment opportunities, salaries, or social regard [@spjwhy]. Journalists may self-organize to improve their public image, but they cannot enjoy the largest benefit of professionalization: they cannot make their trade exclusive.

# Regulation

When information is spread at scale, people will try to regulate it. Whether they claim that the information is 'fake news', too pornographic, defamation, or simply 'socially dangerous', governments and public organizations have tried to quash news and discussion. Journalists, whose job is to create news and discussion, are at particular danger. Recognizing the danger of censorship, most Western governments have enacted protections of the right to free speech. It is exactly these protections that prevent journalism from fully becoming a profession. In fact, some journalists *resist* the label of professional precisely because of the threat to free speech that professionalization would entail [@aquinn2018].

Consider China, where today the press is the "mouthpiece of the Party" [@china]. Here, with utter control of the press by the party, journalists are professionals. The All-China Journalists Association has a comprehensive Code of Ethics which requires journalists to "serve the people wholeheartedly", but "adhere to the correct guidance of public opinion" [@china]. Here, journalism is an exclusive institution, the free press is viewed as a danger to society, and the professionalization of journalists is complete. 

# Conclusion

In the West, it is not possible for journalism to become a profession. Journalists may adopt self-organization, codes of ethics, and publicly undertake their craft to serve a social good, just as other professionals do, but their institution cannot become exclusive without infringing on the right to a free press. Because of their unique relationship with government, journalists cannot professionalize in the way that doctors can. However, such professionalization is clearly possible in countries with despotic and autocratic regimes, where journalists are regulated in the name of the social good. Thus, different countries come to different balances between the desire to allow the press to be free, and the desire to make journalists accountable to the public, and the professionalization of the journalist depends on where those countries end up.

# References