# Power Engineering

| School | School of Engineering | College | College of Science and Engineering |
|--------|-----------------------|---------|------------------------------------|
| Credit level (Normal year taken) | SCQF Level 8 (Year 2 Undergraduate) | Availability | Available to all students |
| SCQF Credits | 10 | ECTS Credits | 5 |

## Summary

This is an introduction course to the techniques and equipment used in the generation, transmission, distribution and utilisation of electrical power.  It gives a basic understanding of how a power system operates and the problems facing electricity utilities. The design and main operating features of different types of motors and generators are also covered.

Course description

- [Introduction to Electrical Circuits](1_Introduction.qmd)
- Introduction to Power Systems
- Electrical Safety &amp; Wiring
- Phasor Representation of AC Signals
- AC Power
- Complex Impedances
- Real &amp; Reactive Power
- Three Phase Systems
- An introduction on electrical machines and transformers
- DC Machines
- Induction Machines
- Synchronous Machines
- Laboratory:
- One 3-hour laboratory, wiring and testing a motor control panel.

Timetable 

<a href="https://www.ted.is.ed.ac.uk/UOE2223_SWS/TIMETABLE.ASP?OBJECTCLASS=MODULE&amp;IDENTIFIER=SCEE08008_SV1_SEM1
&amp;STYLE=TEXTSPREADSHEET&amp;TEMPLATE=SWSCUST+OBJECT+TEXTSPREADSHEET&amp;WEEK=9-19" target="_blank">Timetable</a>

Learning and Teaching activities <a href="http://www.studentsystems.is.ed.ac.uk/staff/Support/User_Guides/CCAM//Teaching_Learning.htm" target="_blank">(Further Info)</a>

## Total Hours: 100
- Lecture Hours 22,
- Seminar/Tutorial Hours 9,
- Supervised Practical/Workshop/Studio Hours 3,
- Formative Assessment Hours 1,
- Summative Assessment Hours 1.5,
- Programme Level Learning and Teaching Hours 2,
- Directed Learning and Independent Learning Hours 61 )


## Assessment <a href="http://www.studentsystems.is.ed.ac.uk/staff/Support/User_Guides/CCAM//Assessment_Methods.htm" target="_blank">(Further Info)</a>

- Written Exam 100 %,
- Coursework 0 %,
- Practical Exam 0 %

Additional Information (Assessment)

100% written examination.

Any student who does not attend and perform satisfactorily on the Power Engineering 2 laboratory is deemed to have failed the course, as it tests Competency regarding important safety aspects of power engineering.

The School has a 40% Rule for 1st and 2nd year courses, i.e. you must achieve a minimum of 40% in coursework and 40% in written exam components, as well as an overall mark of 40% to pass a course. If you fail a course you will be required to re-sit it. You are only required to re-sit components which have been failed.

## Learning Outcomes

On completion of this course, the student will be able to:

- Have a basic understanding of the operation of large electrical power systems, and their main constituent components.
- Understand the operating principles of several different types of electrical machine.
- Be able to perform basic calculations on electrical power systems and machines, while appreciating the limitations of such calculations.
- Have an appreciation of safe practice in the design and construction of electrical power circuits.

## Reading List

Electric Machinery Fundamentals, Stephen
edition, McGraw-Hill, ISBN: 9780071151559

| Course organiser | Dr Paul Judge |
|-------|---------|
| Tel: |   |
| Email: |  paul.judge@ed.ac.uk | 

| Course secretary | Ms Brunori  Viola | 
|------|---------|
| Tel: |  (0131 6)50 5687 | 
| Email: |  vbrunori@ed.ac.uk | 