---
title: Induction Machines
author: Jasper Day
date: Mon 11/21/2022 
---

Induction machines are synchronous machines which make use of induction, rather than a generated magnetic field from permanent or electromagnets. 

Same as the PM synchronous machines, the induction machine generates a rotating magnetic field in the stator from AC current.

:::{.callout-note}

As a quick refresher, recall that there is an electrical frequency and a mechanical frequency. The relationship between them is dictated by the number of pole-pairs (in and out) wound into the stator. 

There is at least one electrical cycle per mechanical cycle, or an integer multiple thereof.

:::

Here is where the difference comes in:

In the rotating magnetic field, you have a stationary copper bar which is shorted. Since the magnetic field is moving, the inductance of the bar creates a voltage:

$$
E \propto -\frac{d\phi_{total}}{dt}
$$

or $E = B\ l\ v = B\ l \ r (\omega_S - \omega_R)$

*Squirrel cages* are induction motors. The amount of force generated by the bars rotating through the magnetic field is dictated by the relative angular velocity between the rotating field of the stator and the rotor.

When the rotor is disconnected from mechanical load, it rotates at *nearly* synchronous speed $N_S$ with angular velocity $\omega_s$. Its rotating speed under load is $N_R$.

The *slip* of the rotor is defined as 

$$
s = \frac{N_S - N_R}{N_S}
$$

At a rotor speed of 0, the induction machine is a transformer with an electrical frequency of $\omega_S / 2\pi$. At synchronous speed, the electrical frequency is zero.

Slip tends to be operated at values of 0.1, 0.5 very close to the synchronous speed. 

# Losses 

Power is lost in the copper and iron of the stator due to hysteresis and eddy currents. 

In the stator with the conductors, the power losses are $I^2\ R$, losses caused by the resistance of the conductors. The *iron* loss is the loss created by hysteresis and eddy currents in the magnetically permeable iron. 

Similarly, in the rotor, the bars create $I^2\ R$ losses; the magnetically permeable cage creates the iron losses.

Power is lost:

1. In the stator
    1. Copper losses (resistance)
    2. Iron losses (hysteresis and eddy currents)
2. In the rotor
    1. Copper losses (resistance)
        This varies linearly with slip: $PR_{loss} = s \ldotp PGAP$
    2. Friction and windage losses

$$
PMECH : PR_{loss}:PGAP = (1-s):s:1
$$

*The mechanical power generated by the rotor (the electromagnetic power) is $1-s$ times the gap power, and the power lost to the rotor is $s$ times the gap power.*

# Phase equivalent circuits

We have inductors and resistors:

- R1 is the stator winding resistance
- R2' is the rotor resistance per fhase referred to the stator winding.
- R2'(1-s)/s is the part of the rotor resistance per phase that produces torque
- X1 is the stator leakage reactance (leakage inductance) created by flux travelling back into the machine.
- X2 is the rotor leakage reactance (leakage inductance)
- XM is the magnetising reactance 

To make this machine easier to analyze, you want to minimize R1 (the stator resistance) and X1 (the leakage flux). Any realistic machine will have $E1 \approx V1$. 

Now the input current is divided only between I0 and I2'. 



Assuming the friction and winding loss = 0, 

$$
T = \frac{3(I'_2)^2R_2'}{s\omega_S}
$$

By our phase diagram, 

$$
I_2' = \frac{V_1}{(R_1 + R_2'/s ) + j(X_1 + X_2')}
$$

Since we're interested in torque, we're only interested in the magnitude of $I_2'$:

$$
\| I_2 \| = \frac{V_1^2}{(R_1 + R_2'/s)^2 + (X_1 + X_2')^2}
$$

# Torque vs Speed

The torque-speed diagram for an induction machine is strikingly different to that of a synchronous machine. It creates the maximum ("pull-out") torque somewhere north and south of synchronicity.

Torque is given by 

$$
T = 3 \left[  \frac{V_1^2}{(R_1 + R_2'/s)^2 + (X_1 + X_2')^2} \right]\frac{R_2'}{s\omega_S}
$$

The stationary points on the torque-slip curve are determined by equating $\frac{dT}{ds} = 0$. This gives you a quadratic equation in s.

At the pull-out point,
$$
s = \frac{\pm R_2'}{\sqrt{R_1^2 + (X_1 + X_2')^2}}
$$

which you would substitute into the equation for torque generated to determine the total torque.

Ideally, your mechanical load would remain within the torque-speed curve at all points. Induction machines can also be used for braking at all points in the curve. 

The current through the stator at stall can be very high, so machines are switched on with a [*soft start*](https://www.electricaltechnology.org/2020/08/soft-starter.html). The soft start chops up the AC waveform with thyristors into small peaks and drops. This gradually ramps up the voltage to the machine, preventing overload of the grid.

# Calculation of Equivalent Circuit Components

## No load test

Here you woudl drive the motor externally to make it run at synchronous speed. At no load, there's no torque being produced, so $I_2' = 0$.

This leaves you with only a resistor and an inductor (the resistance of the coils and the reactance of the stator-rotor combination).

## Standstill test

Here you lock the rotor at 0 speed, giving you a fairly bad transformer. This test should be performed at low voltage to prevent overheating from high currents.

Real power is again only dissipated in resistors, so just like in the previous test we can measure the real power loss as the resistance.

Usually we just lump $X_1$ and $X_2'$ together; both of them are very small and in our phase equivalent circuit we don't have much reason to consider them separately.