# Fluid Mechanics 2


| School | School of Engineering | College | College of Science and Engineering |
|--------|-----------------------|---------|------------------------------------|
| Credit level (Normal year taken) | SCQF Level 8 (Year 2 Undergraduate) | Availability | Available to all students |
| SCQF Credits | 10 | ECTS Credits | 5 |

## Summary

The student should develop an awareness of the qualitive behaviour of fluids in typical situations so that models of problems can be set up for solution. The course's objectives are to:

1.	Produce quantitative solutions for models derived from some useful applications in the fields of measurement and pipe flow;

2.	Establish enough theoretical background to enable the range of validity of these basic solutions to be understood; and to 

3.	Provide a starting point with respect to terminology and theory for more advanced study in subsequent years.

## Course description

- L1	Properties of  Fluids

Shear stress, viscosity, density, compressibility, surface tension.


- L2	Simple Flow Fields and Phenomena 1

- Laminar and turbulent flow states; flow in a duct, flow over a flat plate; flow round objects; separation &amp; wakes; vortex shedding; drag. 

- L3	Simple Flow Fields and Phenomena 2

Reynolds number; Strouhal number. More simple flow fields; orifice flow, flow round bends. Terminology: external/internal; steady/transient, real/ideal, laminar/turbulent,  compressible/incompressible;  vectors, streamlines &amp; pathlines.

- L4	Introduction to Dimensional Analysis

- L5	Fluid Statics 1

Pressure; variation of pressure with height; 'head'; manometers and other pressure measurement devices.

- L6	Fluid Statics 2

Forces on submerged surfaces - 'centre of pressure', 'centre of force'.

- L7	The Continuity Equation

The continuity equation; flow between plane walls. pipe flow.

- L8	Equations of Motion

Equation of motion along a streamline; steady-state equation (Euler's momentum equation); motion perpendicular to a streamline - significance of pressure gradients.

- L9	Bernouilli¿s Equation

Time dependent Bernoulli equation; Steady state Bernoulli equation.

- L10	Applications of Bernouilli

Example applications of Bernoulli equation: siphons, flow with area change, flow around a pipe bend.

- L11	Velocity and Flow Rate Measurement

Pitot tube &amp; Pitot-static tube. Flow rate measurement - restriction flow meters (general); venturi meter.

- L12	Hydraulic Structures

Orifice plate; reservoir-orifice flow; linked reservoirs; orifice flow under varying head; flow over weirs.

- L13	Laminar and Turbulent Flow

- Laminar flow between plates. Laminar flow through a round pipe - Hagen Poiseuille equation.

- L14	Turbulent Flow in Pipes

Head/pressure losses due to friction; friction coefficient - functional dependency via dimensional analysis.

- L15	Losses in Real Pipes

Moody diagram &amp; equation. 

- L16	Pipe Systems

- Losses in bends and fittings; loss coefficient.

- L17	The Momentum Equation

The momentum equation for steady flow.

- L18	Applications of the Momentum Equation 

Force of jet on plates and vanes; force on pipe bends; head loss due to sudden expansion / contraction

- L19	Revision /  contingency

- L20	Revision /  contingency

## Additional Costs

PPE (lab coat, safety glasses, safety shoes/boots as prescribed by programme handbook).

## Timetable 

<a href="https://www.ted.is.ed.ac.uk/UOE2223_SWS/TIMETABLE.ASP?OBJECTCLASS=MODULE&amp;IDENTIFIER=SCEE08003_SV1_SEM1">Timetable link</a>

Learning and Teaching activities <a href="http://www.studentsystems.is.ed.ac.uk/staff/Support/User_Guides/CCAM//Teaching_Learning.htm" target="_blank">(Further Info)</a></td>

## Total Hours: 100

- Lecture Hours 22,
- Supervised Practical/Workshop/Studio Hours 3,
- Formative Assessment Hours 1,
- Summative Assessment Hours 3.5,
- Programme Level Learning and Teaching Hours 2,
- Directed Learning and Independent Learning Hours 68


## Assessment <a href="http://www.studentsystems.is.ed.ac.uk/staff/Support/User_Guides/CCAM//Assessment_Methods.htm" target="_blank">(Further Info)</a>

- Written Exam 50 %,
- Coursework 50 %,
- Practical Exam 0 %

## Learning Goals

On completion of the course students should be able to:

1.	Qualitatively describe and categorise fluid flow regimes, including internal vs external flows; laminar vs turbulent flows; boundary layers and velocity profiles; separation and wakes.

2. 	Appreciate the importance of Dimensional Analysis techniques and dimensionless parameters in fluid mechanics; Reynolds number; Mach number.

3.	Calculate form and skin friction drag forces using appropriate drag formulae and coefficients.

4.	Solve basic hydrostatics problems involving manometers and submerged surfaces.

5.	Explain the significance of pressure gradients parallel to, and normal to a streamline.

6. 	Understand the concept of continuity, and be able to use the continuity equation to calculate the flow rate in a duct using an appropriate velocity profile;

7.	Understand physical basis of Bernoulli's equation, and apply it in flow measurement (orifice and Venturi meter, Pitot-static tube), and to a variety of problems involving area change and height change.

8.	Solve basic problems involving pressure losses through pipes and pipe bends and fittings.

9. 	Understand the basic Momentum equation and the concept of a control volume. Use the equation to calculate impulse and reaction forces due to the interaction of a fluid stream with objects, and pressure drops.

## Reading List

Civil ¿ Chadwick, Morfett &amp; Borthwick: Hydraulics in Civil and Environmental Engineering, 5th edition, Spon, £38 

Chemical ¿ McCabe, Smith and Harriott: Unit Operations of Chemical Engineering, Intl edition, McGraw Hill, £53

Mechanical ¿ Douglas, Gasiorek, Swaffield &amp; Jack: Fluid Mechanics, 6th edition, Pearson, (with ¿free¿ on-line tools) £47.50

but I suggest that you don¿t rush off and buy¿ try library copies of these and others; consider 2nd hand copies (earlier editions usually fine)

| Course organiser |Prof Tom Bruce | 
|------|--------|
| Tel: |  (0131 6)50 8701 | 
| Email: |  Tom.Bruce@ed.ac.uk | 

| Course secretary | Miss Chloe Fleming | 
| Tel: |   | 
| Email: |  cflemin7@ed.ac.uk | 