---
title: Engineering Mathematics 2B
---

School: School of Engineering

College: College of Science and Engineering

# Summary: 

The course consists of two main themes:

Theme 1: Vector calculus and integration of in two parts, taught in the first half of the term in weeks 1-5, and
Theme 2: Introduction to probability and statistics, at the second half in weeks 6-10.

In the first 10 lectures on theme 1 I will introduce the concepts of scalar and vector fields in 2 and 3 dimensions and give real-world examples of such fields in engineering systems. We will cover differentiation of these fields as well as line, double, triple and surface integration focusing on work and flux integrals. For the second theme we also have a total of 10 lectures, where 2D integration of scalar fields is fundamental, we will introduce the concepts of random events and variables, as well as the axioms of probability, with emphasis on the conditional probabilities, independence, Bayes? theorem, the law of large numbers and the central limit theorem. In the second half of theme 2, we switch from probability to statistics to learn about point estimators from data, their bias and variance, and then interval estimators and how to conduct hypothesis tests using data samples, explain how to compute the p-value and the power of the tests, before we close with an introduction in linear regression and the least squares method which is ubiquitous in engineering analysis.

The course has 2 handwritten coursework assessments with 10% of the credit each, one on each theme, and a final exam on both themes for the remaining 80% of the credit. Each coursework is scheduled for a 10 hour load including preparation reading. There will also be 4 online quizzes, two on each theme that the students are encouraged to do for formative feedback and self-assessment. In every aspect of the delivery and assessment, i.e. lectures, tutorials, coursework, exam questions, themes 1 and 2 carry equal merit.

# Course Outline:

Theme 1: Vector calculus and integration

Lecture 1: Scalar and vector fields, the gradient
Lecture 2: Conservative fields, divergence and curl
Lecture 3: Harmonic fields, vector calculus laws
Lecture 4: Line integration, the work integral
Lecture 5: Flux integrals, scalar line integrals
Lecture 6: Work and flux integrals in polar coordinates
Lecture 7: Double integration, changing the order
Lecture 8: Variable transformations and double integrals in polar
Lecture 9: Green's theorems for work and flux
Lecture 10: Triple integrals, cylindrical coordinates

Theme 2: Applied probability and statistics

Lecture 11: Probability axioms, laws and Venn diagrams
Lecture 12: Independence, conditional probability, Bayes¿ theorem, discrete random variables
Lecture 13: Continuous random variables, random variable transformations
Lecture 14: Joint random variables, conditional distribution, convolution
Lecture 15: Law of large numbers, central limit theorem, sums of random variables
Lecture 16: Maximum likelihood estimator, bias, efficiency and mean squared error
Lecture 17: Confidence intervals, non-rejection regions
Lecture 18: Hypothesis testing, type I & II errors, power of the test, p value
Lecture 19: Critical values and quantiles, Z and T hypothesis tests, Gaussian approximation of the binomial
Lecture 20: Linear regression, least squares

Both themes are supported by tutorial classes every week from week 2 to 11.

For theme 2, students will require to become familiar in using the R statistical software, and they will be assessed on it. Lecture slides and instructor notes which also include solved examples and narrated exercises as well as self-assessment questions and answers will be provided for every lecture's material. Unless specified explicitly in the lectures, all material presented in lecture slides and exercises is examinable.

# Timetable:

[Timetable Link](https://www.ted.is.ed.ac.uk/UOE2223_SWS/TIMETABLE.ASP?OBJECTCLASS=MODULE&IDENTIFIER=SCEE08010_SV1_SEM2&STYLE=TEXTSPREADSHEET&TEMPLATE=SWSCUST+OBJECT+TEXTSPREADSHEET&WEEK=26-37)

Total Hours: 100 ( Lecture Hours 20, Seminar/Tutorial Hours 5, Supervised Practical/Workshop/Studio Hours 5, Formative Assessment Hours 2, Summative Assessment Hours 10, Programme Level Learning and Teaching Hours 2, Directed Learning and Independent Learning Hours 56 )

# Assessment:

Written Exam 80 %, Coursework 20 %, Practical Exam 0 %


