---
title: Week 1
subtitle: Linear constant coefficient homogeneous differential equations
author: Jasper Day
---

# Introduction to Differential Equations

There are two main types of differential equations: *Ordinary* and *partial*. Partial differential lequations involve partial derivatives of vectors; ordinary differential equations do not. These are simpler to solve than partial DEs.

In $\frac{df}{dx}$, f is the *dependent variable* and x is the *independent variable*.

The *order* of a differential equation is the degree of the highest derivative occuring in that equation.

## Linear vs Nonlinear

*Linear equations* are those equations in which the **dependent variables and their derivatives** do not occur as products, raised to powers or in nonlinear functions. *Nonlinear equations* are all other equations. 

## Homogeneous and Nonhomogeneous

### How to arrange differential equations

The terms with the *dependent variable* go on the left hand side (ie $x$ in $\frac{dx}{dt}$), and all terms not containing the dependent variable (either terms containing only the independent variable, in this case $t$, or constant terms) go on the right hand side of the equation.

### Determining

When the terms are [arranged properly](1_Linear_DE.qmd#how-to-arrange-differential-equations), then **if the right hand side of the equation is ZERO** then the equation is **homogeneous**. If the right hand side (terms without the dependent variable) is **NONZERO**, then the equation is **nonhomogeneous**.

In other words, each term in a homogeneous differential equation involves a dependent variable or its derivatives.

## Solutions to differential equations

The solutions to differential equations generally comprise a function space, or family of related functions.

### 1st order linear differential equations

For the equation
$$
a\frac{dx}{dt} + bx = 0, x \ne 0,
$$

with constant coefficients $a$ and $b$, the general solution is 

$$
x = Ae^{mt}, \textnormal{where } am + b = 0
$$

### Second Order DEs

Now consider what happens with a 2nd order DE:

$$
a\frac{d^2x}{dt^2} + b\frac{dx}{dt} + cx = 0, a \ne 0
$$

Substituting $x(t) = e^{mt}$, you get 

$$
\begin{gather}
am^2e^{mt} + bme^{mt} + ce^{mt} = 0 \\
e^{mt}\left( am^2 + bm + c \right) = 0
\end{gather}
$$

So $x(t) = e^{mt}$ is a solution if $am^2 + bm + c = 0$. 

$am^2 + bm + c = 0$ is the characteristic equation. It's a quadratic; it has 2 roots $m_1$ and $m_2$.

#### Distinct real roots

When $m_1$ and $m_2$ are distinct real roots, then 

$x(t) = Ae^{m_1t} + Be^{m_2t}$ (all linear combinations of $e^{m_1t}$ and $e^{m_2t}$.)

#### Complex roots

When $m_1$ and $m_2$ are complex conjugates, it's slightly more complex. $m_1 = \phi + j\psi$ and $m_2 = \phi - j\psi$. 

$$
\begin{align}
x(t) &= Ae^{\phi + j\psi t} + Be^{\phi - j\psi t} \\
&= e^{\phi t} \left( Ae^{j\psi t}  + Be^{-j\psi t}\right) \\
&= e^{\phi t}[(A + B)\cos{\psi t} + j(A - B)\cos{\psi t}]
\end{align}
$$

You may further simplify by making $A + B = C$ and $A - B = D$.

#### The Same Root

If $m_1 = m_2 = k$, then the general solution with linear superposition breaks down (the function vectors are no longer linearly independent and are not sufficient to span a function space).

For a differential equation to have a repeated root at m = k, then 