# Engineering Mathematics 2A



## Course Outline

| School | School of Engineering | College | College of Science and Engineering |
|--------|-----------------------|---------|------------------------------------|
| Credit level (Normal year taken) | SCQF Level 8 (Year 2 Undergraduate) | Availability | Available to all students |
| SCQF Credits | 10 | ECTS Credits | 5 |

## Summary

Ordinary differential equations, transforms and Fourier series with applications to engineering. Linear differential equations, homogeneous and non-homogeneous equations, particular solutions for standard forcings; Laplace transforms and applications; standard Fourier series, half range sine and cosine series, complex form; convergence of Fourier series, differentiation and integration of Fourier series. Introduction to Partial Differential Equations.

## Course description

#

- Linear Differential Equations 1 lecture

- Linear constant coefficient Differential Equations 3  lectures

- Second order linear constant coefficient differential  equations, forcing and damping 2 lectures

#

- Definition, simple transforms, properties, inverse and shift theorem 3 lectures

- Solution of ODEs 3 lectures

#

- Fourier series, coefficients, even/odd functions, linearity,  convergence 2 lectures

- Full range, half-range 2 lectures

- Integration and differentiation of Fourier series 1 lecture

#

- Wave equation, Heat or diffusion equation, Laplace equation  1 lecture

- Solution of wave equation, D'alembert solution, separated  solution  2 lectures


Additional Costs: Students are expected to own a copy of:

1. Modern Engineering Mathematics by Glyn James, Prentice Hall, ISBN 978-0-273-73413-X

2. Advanced Modern Engineering Mathematics by Glyn James, Prentice Hall, ISBN 978-0-273-71923-6

## Total Hours: 100

- Lecture Hours 20,
- Seminar/Tutorial Hours 5,
- Formative Assessment Hours 2,
- Summative Assessment Hours 10,
- Programme Level Learning and Teaching Hours 2,
- Directed Learning and Independent Learning Hours 61

## Assessment

- Written Exam 50 %,
- Coursework 50 %,
- Practical Exam 0 %
    
## Learning Outcomes

On completion of this course, the student will be able to:

- Calculate the solution of engineering problems described by linear, constant coefficient first and higher order differential equations
- Analyse and interpret the solutions to draw conclusions on the system behaviour
- Apply the Laplace transform to solve systems of linear, constant coefficient differential equations and to evaluate the stability of dynamic systems
- Use Fourier series analysis to approximate periodic functions, solve differential equations and analyse the response of systems to periodic forcing
-  Distinguish between ordinary and partial differential equations and solve special cases of the wave equation


| Course organiser | Dr Daniel Friedrich |
|------------------|---------------------|
| Tel: | (0131 6)50 5662 |
| Email: | D.Friedrich@ed.ac.uk |
| Course secretary | Miss Mhairi Sime | 
| Tel: |  (0131 6)50 5687 |
| Email: |  msime2@ed.ac.uk |