# Practical Skills in Engineering

## Course Outline

| Credit level (Normal year taken) | SCQF Level 8 (Year 2 Undergraduate) | Availability | Available to all students |
| SCQF Credits | 10 | ECTS Credits | 5 |


## Summary

The School of Engineering undergraduate degrees in Mechanical Engineering (including joint honours degrees in Electrical and Mechanical Engineering) are accredited by the Institution of Mechanical Engineers.  

Requirements are specified in the Accreditation of Higher Education Programmes (AHEP) and guidelines for academic accreditation provided by the Institution of Mechanical Engineers, and include gaining practical skills.  This course contributes to developing these practical skills through a series of hands-on sessions.

## Course description

Students will achieve a pass in this course when they have completed the following activities:

- Safety induction;

- Design review; and

- Joining and metrology sessions.

## Timing:

10 hours of practical sessions

## Assessment:

- Written Exam 0 %,
- Coursework 0 %,
- Practical Exam 100 %

## Learning goals:

On completion of this course, the student will be able to:

- Understanding of important safety considerations in a workshop environment;
- Ability to complete a successful design review;
- Practical skills in joining and metrology.



| Course organiser | Dr Andrew Downes |
|------------------|------------------|
| Tel: |  (0131 6)50 5660 | 
| Email: |  Andy.Downes@ed.ac.uk |

| Course secretary | Miss Chloe Fleming |
|------------------|--------------------|
| Tel: |   | 
| Email: |  cflemin7@ed.ac.uk | 